<a href="https://colab.research.google.com/github/Jqueen43/Pandas-DataFrames/blob/main/Nigerian_Language_Identifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from huggingface_hub import login
from google.colab import userdata

login()

In [ ]:
import pandas as pd
from huggingface_hub import hf_hub_download
metadata_path = hf_hub_download(
    repo_id="naijavoices/naijavoices-dataset-compressed",
    filename="metadata.csv" ,
    repo_type="dataset"
)

df_naija = pd.read_csv(metadata_path, sep='~', on_bad_lines='skip', low_memory=False)
df_naija = df_naija.rename(columns={'language': 'label'})

# Verify the distribution of Igbo, Yoruba and Hausa text rows
print("NaijaVoices row Counts:")
print(df_naija['label'].value_counts())

NaijaVoices row Counts:
label
hausa     708599
yoruba    622156
igbo      586931
Name: count, dtype: int64

In [4]:
df_text_labels = df_sampled[['text', 'label']].copy()

print("DataFrame with only 'text' and 'label' columns:")
display(df_text_labels.head())

print("\nValue counts of 'label' in the new DataFrame:")
print(df_text_labels['label'].value_counts())

DataFrame with only 'text' and 'label' columns:

                                                      text label
184445   Gbaa mbọ hụ na agbadoro ụgbọ mmiri ahụ tupu ọ pụọ  igbo
247769             A ga-enwe ọbá akwụkwọ ọhụrụ na mahadum?  igbo
446379   Anyị na-aga klaasị dị iche iche n'ụlọ dị iche ...  igbo
390031   Federalụ Rodu Sefuti kor mechiri okporo ụzọ ah...  igbo
1903858      Ọ bụghị mmadụ niile na-ekwe arahụ ụra n'ákwá.  igbo

Value counts of 'label' in the new DataFrame:
label
igbo      5000
hausa     5000
yoruba    5000
Name: count, dtype: int64

In [26]:
display(df_ag_news.head())

                                                text  label label_text
0  Wall St. Bears Claw Back Into the Black (Reute...      2   Business
1  Carlyle Looks Toward Commercial Aerospace (Reu...      2   Business
2  Oil and Economy Cloud Stocks' Outlook (Reuters...      2   Business
3  Iraq Halts Oil Exports from Main Southern Pipe...      2   Business
4  Oil prices soar to all-time record, posing new...      2   Business

In [25]:
# Sample a total of 5000 entries from df_ag_news
# Ensure 'text' and 'label' columns are present
# Use random_state for reproducibility

# First, prepare df_ag_news by ensuring it has 'text' and 'label' columns in the desired format
# (Assuming df_ag_news already has a 'text' column and its 'label' column is convertible)
# We'll just select these columns before sampling to ensure consistency

# If df_ag_news's 'label' column is not yet an integer, convert it (though for this sampling it's not strictly necessary, it's good practice if we were using the labels for filtering).
# df_ag_news['label'] = df_ag_news['label'].astype(int)

# Select 'text' and a dummy 'label' column from df_ag_news, then take a random sample of 5000
# The actual label will be overwritten to 'English' after sampling
df_ag_news_sampled = df_ag_news[['text', 'label']].sample(n=5000, random_state=42).copy()

# Assign 'English' as the label for all sampled AG News entries
df_ag_news_sampled['label'] = 'English'

print("AG News Sampled DataFrame (5000 'English' entries) Head:")
display(df_ag_news_sampled.head())

print("\nAG News Sampled DataFrame (5000 'English' entries) Row Counts:")
print(df_ag_news_sampled['label'].value_counts())

AG News Sampled DataFrame (5000 'English' entries) Head:

                                                    text    label
71787  BBC set for major shake-up, claims newspaper L...  English
67218  Marsh averts cash crunch Embattled insurance b...  English
54066  Jeter, Yankees Look to Take Control (AP) AP - ...  English
7168   Flying the Sun to Safety When the Genesis caps...  English
29618  Stocks Seen Flat as Nortel and Oil Weigh  NEW ...  English

AG News Sampled DataFrame (5000 'English' entries) Row Counts:
label
English    5000
Name: count, dtype: int64

In [27]:
# Combine df_text_labels (from NaijaVoices) and df_ag_news_sampled
df_combined = pd.concat([df_text_labels, df_ag_news_sampled], ignore_index=True)

print("Combined DataFrame Head:")
display(df_combined.head())

print("\nCombined DataFrame Label Value Counts:")
print(df_combined['label'].value_counts())

Combined DataFrame Head:

                                                text label
0  Gbaa mbọ hụ na agbadoro ụgbọ mmiri ahụ tupu ọ pụọ  igbo
1            A ga-enwe ọbá akwụkwọ ọhụrụ na mahadum?  igbo
2  Anyị na-aga klaasị dị iche iche n'ụlọ dị iche ...  igbo
3  Federalụ Rodu Sefuti kor mechiri okporo ụzọ ah...  igbo
4      Ọ bụghị mmadụ niile na-ekwe arahụ ụra n'ákwá.  igbo

Combined DataFrame Label Value Counts:
label
igbo       5000
hausa      5000
yoruba     5000
English    5000
Name: count, dtype: int64